### PR TITLE
Traitors + Kidan + Machinelanguage

### PR DESCRIPTION
**Pull request by walmartcheapo**
Probably the changelogs making it un-merge-able.

### CODE REVIEW

**Comment by walmartcheapo** [comment]
Conflicts are mob/uniform.dmi and obj/clothing/suits.dmi 
Fixing

**Comment by BlueNexus** [comment]
Has this been tested?

**Comment by walmartcheapo** [comment]
Yup.

**Comment by walmartcheapo** [comment]
It appears this is attempting to revert some other changes made by some other devs for some reason--let me try and fix that.

**Comment by walmartcheapo** [comment]
Done. I've tested all the changes I personally made. Feel free to merge.

**Pull request closed without merging**
