### PR TITLE
Allows IPC's to make *buzz, *beep and *ping noises, part II

### PR DESCRIPTION
**Pull request by Spacemanspark**
I managed to make it work without breaking everything.
Please review before merging, though.

### CODE REVIEW

**Comment by BlueNexus** [comment]
Test this, please.

**Comment by Spacemanspark** [comment]
I already did, the screenshot shows it.
Although it couldn't hurt to test it one last time when I get home.

**Comment by BlueNexus** [comment]
Alright. Once you get home, test every type of emote and speech. Tell me when you're done.

**Comment by Spacemanspark** [comment]
Done.
/me emotes work.
"!" emotes work.
"*" emotes work.
Talking works.
Radio speech works.
Non-IPC races cannot use the *beep *buzz and *ping commands.
It's ready when you are.

**Pull request merged**
