### PR TITLE
Orderable Protohumans (V.2)

### PR DESCRIPTION
**Pull request by XanderDox**
Makes Protohumans orderable for 35 points.

### CODE REVIEW

**Comment by BlueNexus** [comment]
Closing and opening for Travis.

**Comment by Lorwp** [comment]
@XanderDox : I seem to be unable to Order the protohumans in testing, as there is not an Option Displayed.
capture2

**Comment by XanderDox** [comment]
@Lorwp Strange... I ran a test server and saw the option, I'll look into it, but it should be there. Hrm.

**Comment by BlueNexus** [comment]
Can you confirm if this is working or not?

**Pull request closed without merging**
