### PR TITLE
Baystation Rebase

### PR DESCRIPTION
**Pull request by BlueNexus**
Just spent a few hours straight doing this, going to have a drink. There shouldn't be any conflicts, but setting up Travis to check would be wise.

### CODE REVIEW

**Comment by Ryan784** [comment]
How does one actually download and test it? Or do we have to manually do so

**Comment by Lorwp** [comment]
@Ryan784: click on 0c06cde , select 'browse files' and download the ZIP.

You can also 'git checkout upstream/bayrebase 2'

**Comment by Ryan784** [comment]
Going through and fixing most of the bugs now.

**Comment by Ryan784** [comment]
Okay, fixed every error that I came across and as of right now, it compiles and runs fine. Wouldn't mind having someone double check mine, though. 

@Lorwp How do I go about 'git checkout upstream/bayrebase 2'?

**Comment by Lorwp** [comment]
@Ryan784:
First run this to add the main repository as a remote if you haven't already
 `git remote add Bluenexus https://GitHub.com/bluenexus/Aphelion-Code`
Then run this to fetch then switch to the commit in this pull request
    `git fetch sshado/Bayrebase2 && git checkout bluenexus/Bayrebase2`
Then optionally make an archive of the repository so you keep your working directory clean
    `git archive -o bayrebase.zip 0c06cde` 
Though I'm guessing you already have done something similar or just have downloaded the zip from GitHub's website.
Edit: fix names, thought it was in the the main repository

**Comment by Isratosh** [comment]
This was done by #135, closed.

**Pull request closed without merging**
