### PR TITLE
Library Renovation

### PR DESCRIPTION
**Pull request by XanderDox**
Complete redesign of the library:
Removes the adult and forbidden knowledge bookshelves
Moves the Librarian desk to the south of the room
Changed the Librarian's back room into a 'Book Processing Room'
Added a study area with windows that can be tinted. (Includes a watercooler!)
Re-arranged all the book shelves to the east side of the room, along with the guest computer.
Setup a crafts table
Two normal sitting areas, both with 'fluffy' items.

### CODE REVIEW

**Comment by Isratosh** [comment]
Could you post some screenshots of everything you've changed?

**Comment by BlueNexus** [comment]
I recommend removing the carpet going under the desk and into the librarian's area. It looks odd.

**Comment by XanderDox** [comment]
Sigh, alright.

**Comment by BlueNexus** [comment]
If this is finished, please post one last screenshot, with the unneeded carpet removed. I will test it to ensure there aren't any step issues.

**Pull request closed without merging**
