### PR TITLE
Chemistry Rework

### PR DESCRIPTION
**Pull request by WkSavage**
This will have to do as I do not have access to my main account. This chemistry rework will focuse on creating a reagent system that is both complex and simple to understand. New effects such as addiction, and a slight tweak to the overdose proc, and the addition of a chemical heater. Chemistry reagents will now be in a tier system. Tier one drugs will be cheap and ineffective. There are usually no side effects to tier one. Tier two will be slightly more expensive, and it would be slightly more effective. There might be an overdose starting at 45-60 units. Tier three would be good working medications that have stronger side effects and possibly a chance for addiction. Tier four will be strong drugs, with a low overdose threshold and a high chance for addiction. Tier five will be special drugs that have very strong positive effects but are easy to become addicted to and overdose on. Tier six is cryo drugs. New "base" chemicals will be used to build into some of these chemicals. Base chemicals will have three tiers, low complexity, medium complexity, and high complexity. The more complex ones will have reagent effects, overdoing, and possibly addiction. The chemical dispenser cartridge system will be tweaked to either automatically slowly regenerate chemicals, or switch back to the energy bar that was seen in unbound travels. Other chemical dispensers (ie the booze machine) would not be effected. New traitor chemicals will be added such as hell water for cultists (more on the way). Several new foods will be added, as well as a slight tweaking of the vending machine (just to make it compatible and add some neat items). Currently all progress has been merging in the new reagent system. Currently the new chemistry heaters, addiction, and overdosing should work. As progress or new ideas are added they will be commented here.

### CODE REVIEW

**Comment by BlueNexus** [comment]
Please adjust the description to actually describe the project. This is not just a progress tracker, this allows us to merge the PR once the project is complete. Treat this as a PR that's still being worked on.

**Comment by wksavageschool** [comment]
This will have to do as I do not have access to my main account. This chemistry rework will focuse on creating a reagent system that is both complex and simple to understand. New effects such as addiction, and a slight tweak to the overdose proc, and the addition of a chemical heater. Chemistry reagents will now be in a tier system. Tier one drugs will be cheap and ineffective. There are usually no side effects to tier one. Tier two will be slightly more expensive, and it would be slightly more effective. There might be an overdose starting at 45-60 units. Tier three would be good working medications that have stronger side effects and possibly a chance for addiction.  Tier four will be strong drugs, with a low overdose threshold and a high chance for addiction. Tier five will be special drugs that have very strong positive effects but are easy to become addicted to and overdose on. Tier six is cryo drugs. New "base" chemicals will be used to build into some of these chemicals. Base chemicals will have three tiers, low complexity, medium complexity, and high complexity. The more complex ones will have reagent effects, overdoing, and possibly addiction. The chemical dispenser cartridge system will be tweaked to either automatically slowly regenerate chemicals, or switch back to the energy bar that was seen in unbound travels. Other chemical dispensers (ie the booze machine) would not be effected. New traitor chemicals will be added such as hell water for cultists (more on the way). Several new foods will be added, as well as a slight tweaking of the vending machine (just to make it compatible and add some neat items). Currently all progress has been merging in the new reagent system. Currently the new chemistry heaters, addiction, and overdosing should work. As progress or new ideas are added they will be commented here.

**Comment by wksavageschool** [comment]
Cleaned up Chemical-Reagents, Chemistry Metabolism, Species Flags, And New Procs. This code is just better and less sloppy then the previous code. This will be finished and pushed when I get home.

**Comment by WkSavage** [comment]
The above have been implemented @wksavageschool . The system is no longer as sloppy.

**Comment by WkSavage** [comment]
This will be moved. Expect this to be pulled after a day or so when I'm able to push my latest commits.

**Pull request closed without merging**
